enhancement: "*-feat-*"
fix: "*-fix-*"
ci: "*-ci-*"
chore: "*-chore-*"
test: "*-test-*"
documentation: "*-docs-*"
build: "*-build-*"
style: "*-style-*"
refactor: "*-refactor-*"
performance: "*-perf-*"
